name: deploy

on: 
  workflow_dispatch:  

jobs:
  first_job:
    runs-on: ubuntu-latest
    env: 
      EnvName: dev 
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3 

      - uses: azure/login@v2
        name: Sign in to Azure
        with:
          creds: ${{ secrets.SERVICE_PRINCIPAL }}

      
      - name: Check Path
        run: |
          pwd
          ls -l
        shell: bash   

      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ vars.RESOURCEGROUPNAME }}
          template: ./InfrastructureAsCode/main.bicep

      - name: step2
        run: echo "step2"
