name: jobs

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "step1"

      - name: step2
        run: echo "step2"



  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Ship it 
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'ship ship ship!'
        color: 'white'
