name: jobs

on: 
  workflow_dispatch:
  issues:
    types: [opened]


jobs:
  first_job:
    runs-on: ubuntu-latest
    env: 
      EnvName: dev
    steps:
      - name: step1
        run: echo "step1 in env $EnvName"

      - name: step2
        run: echo "step2"



  second_jon:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
    - name: Ship it 
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'ship ship ship!'
        color: 'white'
